# Generated by Django 4.1.5 on 2023-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_myfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
