# Generated by Django 4.1.5 on 2023-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_myfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='file',
        ),
        migrations.AddField(
            model_name='myfile',
            name='uploadfile',
            field=models.FileField(default='', upload_to='media/app'),
        ),
    ]
