# Generated by Django 4.1.5 on 2023-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_myfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='uploadfile',
            field=models.FileField(default='', upload_to='app'),
        ),
    ]
